function [Output2V, CurrentA] = importgenericsweep(filename, dataLines)
%IMPORTFILE Import data from a text file
%  [BIASV, CURRENTA] = IMPORTFILE(FILENAME) reads data from text file
%  FILENAME for the default selection.  Returns the data as column
%  vectors.
%
%  [BIASV, CURRENTA] = IMPORTFILE(FILE, DATALINES) reads data for the
%  specified row interval(s) of text file FILENAME. Specify DATALINES as
%  a positive scalar integer or a N-by-2 array of positive scalar
%  integers for dis-contiguous row intervals.
%
%  Example:
%  [BiasV, CurrentA] = importfile("/Users/jcyu/Documents/MATLAB/Nanonis/061419/0.01mV00001.dat", [22, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 14-Jun-2019 14:29:09

%% Input handling

%% Find starting line of data (2 lines after [DATA])
fid = fopen(filename);
i = 1;
while(~strcmp(fgetl(fid),'[DATA]'))
    i = i+1;
end
i = i + 2;
fclose(fid);

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [i, Inf];
end

%% Setup the Import Options
opts = delimitedTextImportOptions("NumVariables", 2);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = "\t";

% Specify column names and types
opts.VariableNames = ["Output2V", "CurrentA"];
opts.VariableTypes = ["double", "double"];
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
tbl = readtable(filename, opts);

%% Convert to output type
Output2V = tbl.Output2V;
CurrentA = tbl.CurrentA;
end