function [Experiment, biasspectroscopy, VarName3] = importbiasspectr(filename, dataLines)
%IMPORTFILE Import data from a text file
%  [EXPERIMENT, BIASSPECTROSCOPY, VARNAME3] = IMPORTFILE(FILENAME) reads
%  data from text file FILENAME for the default selection.  Returns the
%  data as column vectors.
%
%  [EXPERIMENT, BIASSPECTROSCOPY, VARNAME3] = IMPORTFILE(FILE,
%  DATALINES) reads data for the specified row interval(s) of text file
%  FILENAME. Specify DATALINES as a positive scalar integer or a N-by-2
%  array of positive scalar integers for dis-contiguous row intervals.
%
%  Example:
%  [Experiment, biasspectroscopy, VarName3] = importfile("C:\Users\STM\Desktop\Stanford University\20190731\BiasSpectroscopy00001.dat", [19, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 01-Aug-2019 12:39:12


% Only read Bias, Current and Output 2 (V) from the file. 

%% Input handling

%% Find starting line of data (2 lines after [DATA])
fid = fopen(filename);
i = 1;
while(~strcmp(fgetl(fid),'[DATA]'))
    i = i+1;
end
i = i + 2;
fclose(fid);

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [i, Inf];
end

%% Setup the Import Options
opts = delimitedTextImportOptions("NumVariables", 3);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = "\t";

% Specify column names and types
opts.VariableNames = ["Experiment", "biasspectroscopy", "VarName3"];
opts.VariableTypes = ["double", "double", "double"];
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
tbl = readtable(filename, opts);

%% Convert to output type
% Only read Bias, Current and Output 2 (V) from the file. 
Experiment = tbl.Experiment;
biasspectroscopy = tbl.biasspectroscopy;
VarName3 = tbl.VarName3;
end